


function test_suite_syntax()
{

  COROUTINE

  ON_INIT

  ON_CANCEL

  BEGIN 

    IF THEN END
    IF THEN PASS END
    IF THEN ELSE END
    IF THEN ELIF THEN END
    IF THEN ELIF THEN ELIF THEN END
    IF THEN ELIF THEN ELSE END
    IF THEN ELIF THEN ELIF THEN ELSE END
  
    IF THEN IF THEN END END
    IF THEN IF THEN END PASS END
    IF THEN IF THEN END ELSE END
    IF THEN IF THEN END ELIF THEN END
    IF THEN IF THEN END ELIF THEN ELIF THEN END
    IF THEN IF THEN END ELIF THEN ELSE END
    IF THEN IF THEN END ELIF THEN ELIF THEN ELSE END
  
    FOR COND ITER THEN END
  
    WHILE THEN END
    REPEAT THEN END
    FOREACH IN THEN END

    AWAIT PASS
    DELAY 10 SECONDS 
    YIELD PASS
    PAUSE PASS
  
    FOR COND ITER THEN
      AWAIT PASS
      DELAY MILLIS 
      YIELD PASS
      PAUSE PASS
  
    END
    
    LOOP END
    LOOP LOOP END END
  

  FINISH DISPATCH
}




