// THIS SCRIPT CONTENTS ARE GENERATED BY BUILDER!
function __KorutiiniSugar_GENERATED() 
{
//=============================================================
var _entrypoints = ds_map_create();
//=============================================================
// 
ds_map_add(_entrypoints, "Example@10",  
KORUTIINI
BEGIN
  
  
FINISH);
//=============================================================
return _entrypoints;
}
//=============================================================
